language: rust
rust:
  - stable
  - beta
  - nightly
env:

matrix:
  include:
    - rust: nightly
      env: RUSTFMT=true
  allow_failures:
    - rust: nightly
      env:
    - rust: nightly
      env: RUSTFMT=true

before_script:
- |
  if [ "${RUSTFMT}" ]; then
    rustup component add rustfmt-preview
  fi

script:
- |
  if [ "${RUSTFMT}" ]; then
    cargo fmt --all -- --check
  else
    cargo test --all --verbose
  fi
